# Generated by Django 5.2.14 on 2026-05-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_region_availabilityblock_appointment_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_preference',
            field=models.CharField(choices=[('email', 'Courriel'), ('sms', 'Texto'), ('phone', 'Téléphone')], default='phone', max_length=20),
        ),
    ]
