# Generated by Django 5.2.14 on 2026-05-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('prescription', 'Prescription / requête médicale'), ('photo', 'Photo'), ('other', 'Autre document')], default='prescription', max_length=50),
        ),
    ]
