# Generated by Django 5.2.14 on 2026-05-17 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_medicaldocument_document_type'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldocument',
            name='appointment',
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='patient_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patientprofile'),
            preserve_default=False,
        ),
    ]
